# Generated by Django 4.0 on 2021-12-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='fot_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%y/'),
        ),
    ]
