# Generated by Django 4.0 on 2021-12-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_fot_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='fot_receita',
            new_name='foto_receita',
        ),
    ]
